# Generated by Django 5.0.3 on 2024-03-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(choices=[('IN', 'Indian'), ('CH', 'Chinese'), ('PH', 'Filipino'), ('OT', 'Others')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
